# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/felipe/workspace/ToPs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/felipe/workspace/ToPs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felipe/workspace/ToPs/CMakeFiles /home/felipe/workspace/ToPs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felipe/workspace/ToPs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ToPS

# Build rule for target.
ToPS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ToPS
.PHONY : ToPS

# fast build rule for target.
ToPS/fast:
	$(MAKE) -f src/CMakeFiles/ToPS.dir/build.make src/CMakeFiles/ToPS.dir/build
.PHONY : ToPS/fast

#=============================================================================
# Target rules for targets named align

# Build rule for target.
align: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 align
.PHONY : align

# fast build rule for target.
align/fast:
	$(MAKE) -f app/CMakeFiles/align.dir/build.make app/CMakeFiles/align.dir/build
.PHONY : align/fast

#=============================================================================
# Target rules for targets named bayes_classifier

# Build rule for target.
bayes_classifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bayes_classifier
.PHONY : bayes_classifier

# fast build rule for target.
bayes_classifier/fast:
	$(MAKE) -f app/CMakeFiles/bayes_classifier.dir/build.make app/CMakeFiles/bayes_classifier.dir/build
.PHONY : bayes_classifier/fast

#=============================================================================
# Target rules for targets named choose_path

# Build rule for target.
choose_path: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 choose_path
.PHONY : choose_path

# fast build rule for target.
choose_path/fast:
	$(MAKE) -f app/CMakeFiles/choose_path.dir/build.make app/CMakeFiles/choose_path.dir/build
.PHONY : choose_path/fast

#=============================================================================
# Target rules for targets named evaluate

# Build rule for target.
evaluate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evaluate
.PHONY : evaluate

# fast build rule for target.
evaluate/fast:
	$(MAKE) -f app/CMakeFiles/evaluate.dir/build.make app/CMakeFiles/evaluate.dir/build
.PHONY : evaluate/fast

#=============================================================================
# Target rules for targets named kullback_positional

# Build rule for target.
kullback_positional: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kullback_positional
.PHONY : kullback_positional

# fast build rule for target.
kullback_positional/fast:
	$(MAKE) -f app/CMakeFiles/kullback_positional.dir/build.make app/CMakeFiles/kullback_positional.dir/build
.PHONY : kullback_positional/fast

#=============================================================================
# Target rules for targets named mea_decoding

# Build rule for target.
mea_decoding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mea_decoding
.PHONY : mea_decoding

# fast build rule for target.
mea_decoding/fast:
	$(MAKE) -f app/CMakeFiles/mea_decoding.dir/build.make app/CMakeFiles/mea_decoding.dir/build
.PHONY : mea_decoding/fast

#=============================================================================
# Target rules for targets named one_file_model

# Build rule for target.
one_file_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 one_file_model
.PHONY : one_file_model

# fast build rule for target.
one_file_model/fast:
	$(MAKE) -f app/CMakeFiles/one_file_model.dir/build.make app/CMakeFiles/one_file_model.dir/build
.PHONY : one_file_model/fast

#=============================================================================
# Target rules for targets named posterior_decoding

# Build rule for target.
posterior_decoding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 posterior_decoding
.PHONY : posterior_decoding

# fast build rule for target.
posterior_decoding/fast:
	$(MAKE) -f app/CMakeFiles/posterior_decoding.dir/build.make app/CMakeFiles/posterior_decoding.dir/build
.PHONY : posterior_decoding/fast

#=============================================================================
# Target rules for targets named posterior_probabilities

# Build rule for target.
posterior_probabilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 posterior_probabilities
.PHONY : posterior_probabilities

# fast build rule for target.
posterior_probabilities/fast:
	$(MAKE) -f app/CMakeFiles/posterior_probabilities.dir/build.make app/CMakeFiles/posterior_probabilities.dir/build
.PHONY : posterior_probabilities/fast

#=============================================================================
# Target rules for targets named predalign

# Build rule for target.
predalign: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predalign
.PHONY : predalign

# fast build rule for target.
predalign/fast:
	$(MAKE) -f app/CMakeFiles/predalign.dir/build.make app/CMakeFiles/predalign.dir/build
.PHONY : predalign/fast

#=============================================================================
# Target rules for targets named print_graph_from_model

# Build rule for target.
print_graph_from_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print_graph_from_model
.PHONY : print_graph_from_model

# fast build rule for target.
print_graph_from_model/fast:
	$(MAKE) -f app/CMakeFiles/print_graph_from_model.dir/build.make app/CMakeFiles/print_graph_from_model.dir/build
.PHONY : print_graph_from_model/fast

#=============================================================================
# Target rules for targets named profileHMMtests

# Build rule for target.
profileHMMtests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 profileHMMtests
.PHONY : profileHMMtests

# fast build rule for target.
profileHMMtests/fast:
	$(MAKE) -f app/CMakeFiles/profileHMMtests.dir/build.make app/CMakeFiles/profileHMMtests.dir/build
.PHONY : profileHMMtests/fast

#=============================================================================
# Target rules for targets named remove_invalid_symbols

# Build rule for target.
remove_invalid_symbols: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 remove_invalid_symbols
.PHONY : remove_invalid_symbols

# fast build rule for target.
remove_invalid_symbols/fast:
	$(MAKE) -f app/CMakeFiles/remove_invalid_symbols.dir/build.make app/CMakeFiles/remove_invalid_symbols.dir/build
.PHONY : remove_invalid_symbols/fast

#=============================================================================
# Target rules for targets named runAllPredalignTests

# Build rule for target.
runAllPredalignTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runAllPredalignTests
.PHONY : runAllPredalignTests

# fast build rule for target.
runAllPredalignTests/fast:
	$(MAKE) -f app/CMakeFiles/runAllPredalignTests.dir/build.make app/CMakeFiles/runAllPredalignTests.dir/build
.PHONY : runAllPredalignTests/fast

#=============================================================================
# Target rules for targets named simulate

# Build rule for target.
simulate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulate
.PHONY : simulate

# fast build rule for target.
simulate/fast:
	$(MAKE) -f app/CMakeFiles/simulate.dir/build.make app/CMakeFiles/simulate.dir/build
.PHONY : simulate/fast

#=============================================================================
# Target rules for targets named simulateAlignment

# Build rule for target.
simulateAlignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulateAlignment
.PHONY : simulateAlignment

# fast build rule for target.
simulateAlignment/fast:
	$(MAKE) -f app/CMakeFiles/simulateAlignment.dir/build.make app/CMakeFiles/simulateAlignment.dir/build
.PHONY : simulateAlignment/fast

#=============================================================================
# Target rules for targets named sliding_window

# Build rule for target.
sliding_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sliding_window
.PHONY : sliding_window

# fast build rule for target.
sliding_window/fast:
	$(MAKE) -f app/CMakeFiles/sliding_window.dir/build.make app/CMakeFiles/sliding_window.dir/build
.PHONY : sliding_window/fast

#=============================================================================
# Target rules for targets named test_read_seq

# Build rule for target.
test_read_seq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_read_seq
.PHONY : test_read_seq

# fast build rule for target.
test_read_seq/fast:
	$(MAKE) -f app/CMakeFiles/test_read_seq.dir/build.make app/CMakeFiles/test_read_seq.dir/build
.PHONY : test_read_seq/fast

#=============================================================================
# Target rules for targets named testeFBGHMM

# Build rule for target.
testeFBGHMM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testeFBGHMM
.PHONY : testeFBGHMM

# fast build rule for target.
testeFBGHMM/fast:
	$(MAKE) -f app/CMakeFiles/testeFBGHMM.dir/build.make app/CMakeFiles/testeFBGHMM.dir/build
.PHONY : testeFBGHMM/fast

#=============================================================================
# Target rules for targets named testeGPHMM

# Build rule for target.
testeGPHMM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testeGPHMM
.PHONY : testeGPHMM

# fast build rule for target.
testeGPHMM/fast:
	$(MAKE) -f app/CMakeFiles/testeGPHMM.dir/build.make app/CMakeFiles/testeGPHMM.dir/build
.PHONY : testeGPHMM/fast

#=============================================================================
# Target rules for targets named train

# Build rule for target.
train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train
.PHONY : train

# fast build rule for target.
train/fast:
	$(MAKE) -f app/CMakeFiles/train.dir/build.make app/CMakeFiles/train.dir/build
.PHONY : train/fast

#=============================================================================
# Target rules for targets named viterbi_decoding

# Build rule for target.
viterbi_decoding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viterbi_decoding
.PHONY : viterbi_decoding

# fast build rule for target.
viterbi_decoding/fast:
	$(MAKE) -f app/CMakeFiles/viterbi_decoding.dir/build.make app/CMakeFiles/viterbi_decoding.dir/build
.PHONY : viterbi_decoding/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ToPS"
	@echo "... align"
	@echo "... bayes_classifier"
	@echo "... choose_path"
	@echo "... evaluate"
	@echo "... kullback_positional"
	@echo "... mea_decoding"
	@echo "... one_file_model"
	@echo "... posterior_decoding"
	@echo "... posterior_probabilities"
	@echo "... predalign"
	@echo "... print_graph_from_model"
	@echo "... profileHMMtests"
	@echo "... remove_invalid_symbols"
	@echo "... runAllPredalignTests"
	@echo "... simulate"
	@echo "... simulateAlignment"
	@echo "... sliding_window"
	@echo "... test_read_seq"
	@echo "... testeFBGHMM"
	@echo "... testeGPHMM"
	@echo "... train"
	@echo "... viterbi_decoding"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

